class ChangeCustomer {
  String? id,
      typeCustomer,
      noAccount,
      nama,
      namaUpdate,
      agama,
      agamaUpdate,
      tempatLahir,
      tempatLahirUpdate,
      tanggalLahir,
      tanggalLahirUpdate,
      alamat,
      alamatUpdate,
      noTelp,
      noTelpUpdate,
      fax,
      faxUpdate,
      noIdentitas,
      noIdentitasUpdate,
      noNpwp,
      noNpwpUpdate,
      namaUsaha,
      namaUsahaUpdate,
      provinsiUsaha,
      provinsiUsahaUpdate,
      kotaUsaha,
      kotaUsahaUpdate,
      kecamatanUsaha,
      kecamatanUsahaUpdate,
      kelurahanUsaha,
      kelurahanUsahaUpdate,
      alamatUsaha,
      alamatUsahaUpdate,
      telpUsaha,
      telpUsahaUpdate,
      faxUsaha,
      faxUsahaUpdate,
      emailUsaha,
      emailUsahaUpdate,
      namaPj,
      namaPjUpdate,
      ttdCustomer,
      namaSalesman,
      ttdSM,
      namaSM,
      reasonSM,
      dateApprovedSM,
      ttdAR,
      namaAR,
      reasonAR,
      dateApprovedAR,
      status,
      oracle,
      createdBy,
      dateAdded,
      fNameSM,
      fNameAR;

  ChangeCustomer.fromJson(Map json)
      : id = json['id'] ?? '',
        typeCustomer = json['type_customer'] ?? '',
        noAccount = json['no_account'] ?? '',
        nama = json['nama'] ?? '',
        namaUpdate = json['nama_update'] ?? '',
        agama = json['agama'] ?? '',
        agamaUpdate = json['agama_update'] ?? '',
        tempatLahir = json['tempat_lahir'] ?? '',
        tempatLahirUpdate = json['tempat_lahir_update'] ?? '',
        tanggalLahir = json['tanggal_lahir'] ?? '',
        tanggalLahirUpdate = json['tanggal_lahir_update'] ?? '',
        alamat = json['alamat'] ?? '',
        alamatUpdate = json['alamat_update'] ?? '',
        noTelp = json['no_telp'] ?? '',
        noTelpUpdate = json['no_telp_update'] ?? '',
        fax = json['fax'] ?? '',
        faxUpdate = json['fax_update'] ?? '',
        noIdentitas = json['no_identitas'] ?? '',
        noIdentitasUpdate = json['no_identitas_update'] ?? '',
        noNpwp = json['no_npwp'] ?? '',
        noNpwpUpdate = json['no_npwp_update'] ?? '',
        namaUsaha = json['nama_usaha'] ?? '',
        namaUsahaUpdate = json['nama_usaha_update'] ?? '',
        provinsiUsaha = json['provinsi_usaha'] ?? '',
        provinsiUsahaUpdate = json['provinsi_usaha_update'] ?? '',
        kotaUsaha = json['kota_usaha'] ?? '',
        kotaUsahaUpdate = json['kota_usaha_update'] ?? '',
        kecamatanUsaha = json['kecamatan_usaha'] ?? '',
        kecamatanUsahaUpdate = json['kecamatan_usaha_update'] ?? '',
        kelurahanUsaha = json['kelurahan_usaha'] ?? '',
        kelurahanUsahaUpdate = json['kelurahan_usaha_update'] ?? '',
        alamatUsaha = json['alamat_usaha'] ?? '',
        alamatUsahaUpdate = json['alamat_usaha_update'] ?? '',
        telpUsaha = json['telp_usaha'] ?? '',
        telpUsahaUpdate = json['telp_usaha_update'] ?? '',
        faxUsaha = json['fax_usaha'] ?? '',
        faxUsahaUpdate = json['fax_usaha_update'] ?? '',
        emailUsaha = json['email_usaha'] ?? '',
        emailUsahaUpdate = json['email_usaha_update'] ?? '',
        namaPj = json['nama_pj'] ?? '',
        namaPjUpdate = json['nama_pj_update'] ?? '',
        ttdCustomer = json['ttd_customer'] ?? '',
        namaSalesman = json['nama_salesman'] ?? '',
        ttdSM = json['ttd_sales_manager'] ?? '',
        namaSM = json['nama_sales_manager'] ?? '',
        reasonSM = json['reason_sales_manager'] ?? '',
        dateApprovedSM = json['date_approved_sm'] ?? '',
        ttdAR = json['ttd_ar_manager'] ?? '',
        namaAR = json['nama_ar_manager'] ?? '',
        reasonAR = json['reason_ar_manager'] ?? '',
        dateApprovedAR = json['date_approved_am'] ?? '',
        status = json['status'] ?? '',
        oracle = json['oracle'] ?? '',
        createdBy = json['created_by'] ?? '',
        dateAdded = json['date_added'] ?? '',
        fNameSM = json['sm_name'] ?? '',
        fNameAR = json['am_name'] ?? '';

  Map toJson() {
    return {
      'id' : id,
      'type_customer' : typeCustomer,
      'no_account' : noAccount,
      'nama' : nama,
      'nama_update' : namaUpdate,
      'agama' : agama,
      'agama_update' : agamaUpdate,
      'tempat_lahir' : tempatLahir,
      'tempat_lahir_update' : tempatLahirUpdate,
      'tanggal_lahir' : tanggalLahir, 
      'tanggal_lahir_update' : tanggalLahirUpdate, 
      'alamat' : alamat,
      'alamat_update' : alamatUpdate,
      'no_telp' : noTelp,
      'no_telp_update' : noTelpUpdate, 
      'fax' : fax,
      'fax_update' : faxUpdate,
      'no_identitas' : noIdentitas,
      'no_identitas_update' : noIdentitasUpdate,
      'no_npwp' : noNpwp,
      'no_npwp_update' : noNpwpUpdate,
      'nama_usaha' : namaUsaha,
      'nama_usaha_update' : namaUsahaUpdate,
      'provinsi_usaha' : provinsiUsaha,
      'provinsi_usaha_update' : provinsiUsahaUpdate,
      'kota_usaha' : kotaUsaha,
      'kota_usaha_update' : kotaUsahaUpdate,
      'kecamatan_usaha' : kecamatanUsaha,
      'kecamatan_usaha_update' : kecamatanUsahaUpdate,
      'kelurahan_usaha' : kelurahanUsaha,
      'kelurahan_usaha_update' : kelurahanUsahaUpdate,
      'alamat_usaha' : alamatUsaha,
      'alamat_usaha_update' : alamatUsahaUpdate,
      'telp_usaha' : telpUsaha,
      'telp_usaha_update' : telpUsahaUpdate,
      'fax_usaha' : faxUsaha,
      'fax_usaha_update' : faxUsahaUpdate,
      'email_usaha' : emailUsaha,
      'email_usaha_update' : emailUsahaUpdate,
      'nama_pj' : namaPj,
      'nama_pj_update' : namaPjUpdate,
      'ttd_customer' : ttdCustomer,
      'nama_salesman' : namaSalesman,
      'ttd_sales_manager' : ttdSM,
      'nama_sales_manager' : namaSM,
      'reason_sales_manager' : reasonSM,
      'date_approved_sm' : dateApprovedSM,
      'ttd_ar_manager' : ttdAR,
      'nama_ar_manager' : namaAR,
      'reason_ar_manager' : reasonAR,
      'date_approved_am' : dateApprovedAR,
      'status' : status,
      'oracle' : oracle,
      'created_by' : createdBy,
      'date_added' : dateAdded,
      'sm_name' : fNameSM,
      'am_name' : fNameAR
    };
  }
}
