class CustomerNoImage {
  String noAccount = '';
  String id,
      nama,
      agama,
      tempatLahir,
      tanggalLahir,
      alamat,
      noTlp,
      fax,
      noIdentitas,
      area,
      namaUsaha,
      provinsiUsaha,
      kotaUsaha,
      kecamatanUsaha,
      kelurahanUsaha,
      alamatUsaha,
      tlpUsaha,
      faxUsaha,
      emailUsaha,
      namaPj,
      sistemPembayaran,
      kreditLimit,
      ttdCustomer,
      ttdArManager,
      ttdSalesManager,
      namaSalesman,
      namaArManager,
      note,
      econtract,
      status,
      isRevisi,
      createdBy,
      dateAdded;
  String dateSM = '';
  String dateAM = '';
  String noNpwp = '';

  CustomerNoImage.fromJson(Map json)
      : area = json['area'] ?? '',
        noAccount = json['no_account'] ?? '',
        id = json['id'],
        nama = json['nama'],
        agama = json['agama'],
        tempatLahir = json['tempat_lahir'],
        tanggalLahir = json['tanggal_lahir'],
        alamat = json['alamat'],
        noTlp = json['no_telp'],
        fax = json['fax'],
        noIdentitas = json['no_identitas'] ?? '',
        noNpwp = json['no_npwp'] ?? '',
        namaUsaha = json['nama_usaha'] ?? '',
        provinsiUsaha = json['provinsi_usaha'] ?? '',
        kotaUsaha = json['kota_usaha'] ?? '',
        kecamatanUsaha = json['kecamatan_usaha'] ?? '',
        kelurahanUsaha = json['kelurahan_usaha'] ?? '',
        alamatUsaha = json['alamat_usaha'],
        tlpUsaha = json['telp_usaha'],
        faxUsaha = json['fax_usaha'],
        emailUsaha = json['email_usaha'],
        namaPj = json['nama_pj'],
        sistemPembayaran = json['sistem_pembayaran'] ?? '',
        kreditLimit = json['kredit_limit'],
        ttdCustomer = json['ttd_customer'] ?? '',
        namaSalesman = json['nama_salesmanager'] ?? '',
        ttdSalesManager = json['ttd_sales_manager'],
        dateSM = json['date_approved_sm'] ?? '',
        ttdArManager = json['ttd_ar_manager'],
        namaArManager = json['nama_ar_manager'] ?? '',
        dateAM = json['date_approved_am'] ?? '',
        note = json['note'] ?? '',
        econtract = json['e_contract'],
        status = json['status'],
        isRevisi = json['is_revisi'],
        createdBy = json['created_by'],
        dateAdded = json['date_added'];

  Map toJson() {
    return {
      'area': area,
      'no_account': noAccount,
      'id': id,
      'nama': nama,
      'agama': agama,
      'tempat_lahir': tempatLahir,
      'tanggal_lahir': tanggalLahir,
      'alamat': alamat,
      'no_telp': noTlp,
      'fax': fax,
      'no_identitas': noIdentitas,
      'no_npwp': noNpwp,
      'nama_usaha': namaUsaha,
      'provinsi_usaha' : provinsiUsaha,
      'kota_usaha' : kotaUsaha,
      'kecamatan_usaha' : kecamatanUsaha,
      'kelurahan_usaha' : kelurahanUsaha,
      'alamat_usaha': alamatUsaha,
      'telp_usaha': tlpUsaha,
      'fax_usaha': faxUsaha,
      'email_usaha': emailUsaha,
      'nama_pj': namaPj,
      'sistem_pembayaran': sistemPembayaran,
      'kredit_limit': kreditLimit,
      'ttd_customer': ttdCustomer,
      'nama_salesman': namaSalesman,
      'ttd_sales_manager': ttdSalesManager,
      'date_approved_sm': dateSM,
      'ttd_ar_manager': ttdArManager,
      'nama_ar_manager': namaArManager,
      'date_approved_am': dateAM,
      'note': note,
      'e_contract': econtract,
      'status': status,
      'is_revisi': isRevisi,
      'created_by': createdBy,
      'date_added': dateAdded,
    };
  }
}
