class ListPencairanInkaroHeader {
  String pencairanInkaroId,
      nomorPencairan,
      requestDate,
      startPeriode_conv,
      endPeriode_conv,
      startPeriode,
      endPeriode,
      namaOptik,
      shipNumberOptik,
      totalInkaro,
      pphInkaro,
      totalInkaroAfterPPH,
      approvalSM,
      approvalSMName,
      reasonRejectSM,
      dateApprovalSM,
      approvalAM,
      approvalAMName,
      reasonRejectAM,
      dateApprovalAM;

  ListPencairanInkaroHeader.fromJson(Map json)
      : pencairanInkaroId = json['PROCESS_ID'] ?? '',
        nomorPencairan = json['ID_PENCAIRAN'] ?? '',
        requestDate = json['TRX_DATE'] ?? '',
        startPeriode_conv = json['START_DATE_PERIODE_conv'] ?? '',
        endPeriode_conv = json['END_DATE_PERIODE_conv'] ?? '',
        startPeriode = json['START_DATE_PERIODE'] ?? '',
        endPeriode = json['END_DATE_PERIODE'] ?? '',
        namaOptik = json['SHIP_NAME'] ?? '',
        shipNumberOptik = json['SHIP_LOCATION'] ?? '',
        totalInkaro = json['TOTAL_INKARO'] ?? '',
        pphInkaro = json['PPH'] ?? '',
        totalInkaroAfterPPH = json['TOTAL_INKARO_PPH'] ?? '',
        approvalSM = json['approval_sm'] ?? '',
        approvalAM = json['approval_am'] ?? '',
        reasonRejectSM = json['reason_sm'] ?? '',
        reasonRejectAM = json['reason_am'] ?? '',
        dateApprovalSM = json['date_approval_sm'] ?? '',
        dateApprovalAM = json['date_approval_am'] ?? '',
        approvalSMName = json['approver_sm_name'] ?? '',
        approvalAMName = json['approver_am_name'] ?? '';

  Map toJson() {
    return {
      'PROCESS_ID': pencairanInkaroId,
      'ID_PENCAIRAN': nomorPencairan,
      'TRX_DATE': requestDate,
      'START_DATE_PERIODE_conv': startPeriode_conv,
      'END_DATE_PERIODE_conv': endPeriode_conv,
      'START_DATE_PERIODE': startPeriode,
      'END_DATE_PERIODE': endPeriode,
      'SHIP_NAME': namaOptik,
      'SHIP_LOCATION': shipNumberOptik,
      'TOTAL_INKARO': totalInkaro,
      'PPH': pphInkaro,
      'TOTAL_INKARO_PPH': totalInkaroAfterPPH,
      'approval_sm': approvalSM,
      'approval_am': approvalAM,
      'approver_sm_name': approvalSMName,
      'approver_am_name': approvalAMName,
      'reason_sm': reasonRejectSM,
      'reason_am': reasonRejectAM,
      'date_approval_sm': dateApprovalSM,
      'date_approval_am': dateApprovalAM
    };
  }
}
