class ListInkaroHeader {
  String inkaroContractId,
      noAccount,
      startPeriode,
      endPeriode,
      nikKTP,
      npwp,
      namaStaff,
      anRekening,
      bank,
      namaBank,
      nomorRekening,
      telpKonfirmasi,
      approvalSM,
      reasonSM,
      status,
      notes,
      customerShipName,
      addressShipName,
      createdById,
      createdByName;

  ListInkaroHeader.fromJson(Map json)
      : inkaroContractId = json['id_inkaro_contract'],
        noAccount = json['CUSTOMER_SHIP_NUMBER'],
        startPeriode = json['start_periode'] ?? '',
        endPeriode = json['end_periode'] ?? '',
        nikKTP = json['nik_ktp'],
        npwp = json['npwp'],
        namaStaff = json['nama_staff'],
        anRekening = json['an_rekening'],
        bank = json['bank'],
        namaBank = json['nama_bank'],
        nomorRekening = json['nomor_rekening'],
        telpKonfirmasi = json['telp_konfirmasi'],
        approvalSM = json['approval_sm'],
        reasonSM = json['reason_sm'],
        status = json['status'],
        notes = json['notes'],
        customerShipName = json['CUSTOMER_SHIP_NAME'],
        addressShipName = json['ADDRESS'],
        createdByName = json['SALES_NAME'],
        createdById = json['create_by'];

  Map toJson() {
    return {
      'id_inkaro_contract': inkaroContractId,
      'CUSTOMER_SHIP_NUMBER': noAccount,
      'nama_usaha': startPeriode,
      'alamat_usaha': endPeriode,
      'nik_ktp': nikKTP,
      'npwp': npwp,
      'nama_staff': namaStaff,
      'an_rekening': anRekening,
      'bank': bank,
      'nama_bank': namaBank,
      'nomor_rekening': nomorRekening,
      'telp_konfirmasi': telpKonfirmasi,
      'approval_sm': approvalSM,
      'reason_sm': reasonSM,
      'status': status,
      'notes': notes,
      'CUSTOMER_SHIP_NAME': customerShipName,
      'ADDRESS': addressShipName,
      'SALES_NAME': createdByName,
      'create_by': createdById
    };
  }
}
