class MarketingExpenseHeader {
  String? id,
      salesName,
      shipNumber,
      billNumber,
      opticName,
      opticAddress,
      opticType,
      dataName,
      dataNik,
      dataNpwp,
      isSpSatuan,
      spNumber,
      isSpPercent,
      spStartPeriode,
      spEndPeriode,
      totalValue,
      totalPercent,
      paymentMechanism,
      paymentDate,
      idRekening,
      notes,
      isTraining,
      trainingMekanisme,
      trainingMateri,
      trainingDate,
      trainingTime,
      trainingDuration,
      approvalSM,
      approverSM,
      reasonSM,
      dateApprovalSM,
      approvalADM,
      approverADM,
      reasonADM,
      dateApprovalADM,
      approvalGM,
      approverGM,
      reasonGM,
      dateApprovalGM,
      status,
      createdBy,
      insertDate,
      updateDate,
      updateBy,
      smName,
      admName,
      gmName, 
      accountNumber,
      accountName, 
      bankName;

  MarketingExpenseHeader();

  MarketingExpenseHeader.fromJson(Map json)
      : id = json['id_marketing_expense'],
        salesName = json['salesname'],
        shipNumber = json['customer_ship_number'],
        billNumber = json['bill_number'],
        opticName = json['optic_name'],
        opticAddress = json['optic_address'],
        opticType = json['optic_type'],
        dataName = json['data_name'],
        dataNik = json['data_nik'],
        dataNpwp = json['data_npwp'],
        isSpSatuan = json['is_sp_satuan'],
        spNumber = json['sp_number'],
        isSpPercent = json['is_sp_percent'],
        spStartPeriode = json['sp_start_period'],
        spEndPeriode = json['sp_end_period'],
        totalValue = json['total_value'],
        totalPercent = json['total_percent'],
        paymentMechanism = json['payment_mechanism'],
        paymentDate = json['payment_date'],
        idRekening = json['id_rekening'],
        notes = json['notes'],
        isTraining = json['is_training'],
        trainingMekanisme = json['training_mekanisme'],
        trainingMateri = json['training_materi'],
        trainingDate = json['training_date'] ?? '',
        trainingTime = json['training_time'] ?? '',
        trainingDuration = json['training_duration'] ?? '',
        approvalSM = json['approval_sm'],
        approverSM = json['approver_sm'] ?? '',
        reasonSM = json['reason_sm'] ?? '',
        dateApprovalSM = json['date_approval_sm'] ?? '2024-01-01 08:00:00',
        approvalADM = json['approval_adm'],
        approverADM = json['approver_adm'] ?? '',
        reasonADM = json['reason_adm'] ?? '',
        dateApprovalADM = json['date_approval_adm'] ?? '2024-01-01 08:00:00',
        approvalGM = json['approval_gm'],
        approverGM = json['approver_gm'] ?? '',
        reasonGM = json['reason_gm'] ?? '',
        dateApprovalGM = json['date_approval_gm'] ?? '2024-01-01 08:00:00',
        status = json['status'],
        createdBy = json['created_by'] ?? '',
        insertDate = json['insert_date'] ?? '',
        updateBy = json['update_by'] ?? '',
        updateDate = json['update_date'] ?? '',
        smName = json['sm_name'] ?? '',
        admName = json['adm_name'] ?? '',
        gmName = json['gm_name'] ?? '',
        accountNumber = json['account_number'] ?? '',
        accountName = json['account_name'] ?? '',
        bankName = json['shortname_bank'];

  Map toJson() {
    return {
      'id_marketing_expense': id,
      'salesname': salesName,
      'customer_ship_number': shipNumber,
      'bill_number': billNumber,
      'optic_name': opticName,
      'optic_address': opticAddress,
      'optic_type': opticType,
      'data_name': dataName,
      'data_nik': dataNik,
      'data_npwp': dataNpwp,
      'is_sp_satuan': isSpSatuan,
      'sp_number': spNumber,
      'is_sp_percent': isSpPercent,
      'sp_start_period': spStartPeriode,
      'sp_end_period': spEndPeriode,
      'total_value': totalValue,
      'total_percent': totalPercent,
      'payment_mechanism': paymentMechanism,
      'payment_date': paymentDate,
      'id_rekening': idRekening,
      'notes': notes,
      'is_training': isTraining,
      'training_mekanisme': trainingMekanisme,
      'training_materi': trainingMateri,
      'training_date': trainingDate,
      'training_time': trainingTime,
      'training_duration': trainingDuration,
      'approval_sm': approvalSM,
      'approver_sm': approverSM,
      'reason_sm': reasonSM,
      'date_approval_sm': dateApprovalSM,
      'approval_adm': approvalADM,
      'approver_adm': approverADM,
      'reason_adm': reasonADM,
      'date_approval_adm': dateApprovalADM,
      'approval_gm': approvalGM,
      'approver_gm': approverGM,
      'reason_gm': reasonGM,
      'date_approval_gm': dateApprovalGM,
      'status': status,
      'created_by': createdBy,
      'insert_date': insertDate,
      'update_by': updateBy,
      'update_date': updateDate,
      'sm_name': smName,
      'adm_name': admName,
      'gm_name': gmName,
      'account_number' : accountNumber,
      'account_name' : accountName,
      'shortname_bank' : bankName,
    };
  }
}
